
package io.opsapplication.opsservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Ops", targetNamespace = "http://opsApplication.io/OpsService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Ops {


    /**
     * 
     * @param request
     * @return
     *     returns io.opsapplication.opsservice.DocumentMetadata
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "createDocument", targetNamespace = "http://opsApplication.io/OpsService/", className = "io.opsapplication.opsservice.CreateDocument")
    @ResponseWrapper(localName = "createDocumentResponse", targetNamespace = "http://opsApplication.io/OpsService/", className = "io.opsapplication.opsservice.CreateDocumentResponse")
    public DocumentMetadata createDocument(
        @WebParam(name = "request", targetNamespace = "")
        DocumentMetadata request);

}
