package io.opsapplication.opsservice;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Ops", targetNamespace = "http://opsApplication.io/OpsService/",
        wsdlLocation = "file:/C:/Test/opsservice/src/main/resource/OpsService.wsdl")
public class OpsClientService
    extends Service
{

    private final static URL OPS_WSDL_LOCATION;
    private final static WebServiceException OPS_EXCEPTION;
    private final static QName OPS_QNAME = new QName("http://opsApplication.io/OpsService/", "Ops");

    static {
        URL url = null;
        WebServiceException e = null;
        url = OpsClientService.class.getResource("/META-INF/wsdl//OpsService.wsdl");
        if (url==null) {

        }
        OPS_WSDL_LOCATION = url;
        OPS_EXCEPTION = e;
    }

    public OpsClientService() {
        super(__getWsdlLocation(), OPS_QNAME);
    }

    public OpsClientService(WebServiceFeature... features) {
        super(__getWsdlLocation(), OPS_QNAME, features);
    }

    public OpsClientService(URL wsdlLocation) {
        super(wsdlLocation, OPS_QNAME);
    }

    public OpsClientService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OPS_QNAME, features);
    }

    public OpsClientService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OpsClientService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Ops
     */
    @WebEndpoint(name = "OpsPort")
    public Ops getOpsPort() {
        return super.getPort(new QName("http://opsApplication.io/OpsService/", "OpsPort"), Ops.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Ops
     */
    @WebEndpoint(name = "OpsPort")
    public Ops getOpsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://opsApplication.io/OpsService/", "OpsPort"), Ops.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OPS_EXCEPTION!= null) {
            throw OPS_EXCEPTION;
        }
        return OPS_WSDL_LOCATION;
    }

}
